/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-fixed-dim': '#89ceff',
        error: '#ba1a1a',
        'surface-container': '#e7eefe',
        'primary-fixed-dim': '#c3c0ff',
        'on-background': '#151c27',
        'on-tertiary-container': '#67f4b7',
        surface: '#f9f9ff',
        'on-primary-fixed': '#0f0069',
        'primary-container': '#4f46e5',
        'secondary-fixed': '#c9e6ff',
        primary: '#3525cd',
        'surface-bright': '#f9f9ff',
        'on-primary-fixed-variant': '#3323cc',
        'outline-variant': '#c7c4d8',
        'error-container': '#ffdad6',
        outline: '#777587',
        'inverse-surface': '#2a313d',
        secondary: '#006591',
        'on-secondary-fixed': '#001e2f',
        'surface-dim': '#d3daea',
        'primary-fixed': '#e2dfff',
        'inverse-primary': '#c3c0ff',
        'tertiary-fixed-dim': '#4edea3',
        'on-secondary-container': '#004666',
        'surface-container-highest': '#dce2f3',
        'on-tertiary-fixed-variant': '#005236',
        'on-surface-variant': '#464555',
        'secondary-container': '#39b8fd',
        'surface-container-low': '#f0f3ff',
        'surface-tint': '#4d44e3',
        'on-secondary-fixed-variant': '#004c6e',
        tertiary: '#005338',
        'on-surface': '#151c27',
        'on-primary-container': '#dad7ff',
        'surface-container-lowest': '#ffffff',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        'surface-variant': '#dce2f3',
        'on-tertiary-fixed': '#002113',
        'surface-container-high': '#e2e8f8',
        background: '#f9f9ff',
        'on-primary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'inverse-on-surface': '#ebf1ff',
        'tertiary-container': '#006e4b',
        'tertiary-fixed': '#6ffbbe',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'gutter-mobile': '0.75rem',
        'space-lg': '1.5rem',
        'space-sm': '0.5rem',
        margin: '2rem',
        'space-xl': '2rem',
        gutter: '1.5rem',
        'space-xs': '0.25rem',
        'margin-mobile': '1rem',
        'space-md': '1rem',
      },
      fontFamily: {
        'body-md': ['Inter'],
        'headline-lg-mobile': ['Plus Jakarta Sans'],
        'headline-lg': ['Plus Jakarta Sans'],
        'label-sm': ['Inter'],
        'label-md': ['Inter'],
        'body-lg': ['Inter'],
        'headline-xl': ['Plus Jakarta Sans'],
        'headline-sm': ['Plus Jakarta Sans'],
        'body-sm': ['Inter'],
        'headline-xl-mobile': ['Plus Jakarta Sans'],
        'numeric-metric': ['Plus Jakarta Sans'],
        'headline-md': ['Plus Jakarta Sans'],
        'body-xs': ['Inter'],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-lg-mobile': ['20px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '600' }],
        'label-md': ['13px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-xl': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '600' }],
        'body-sm': ['13px', { lineHeight: '18px', letterSpacing: '0.005em', fontWeight: '400' }],
        'headline-xl-mobile': ['26px', { lineHeight: '34px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'numeric-metric': ['28px', { lineHeight: '34px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['18px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-xs': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
